### ISSUE TITLE
执行sim.get_score("hello","hello") 报错。

### ISSUE THREAD

**Issue by melisa81** [shibing624/text2vec#147]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/text2vec/similarity.py", line 104, in get_score
    res = cos_sim(emb1, emb2)[0] if self.embedding_type == EmbeddingType.BERT else cosine_distance(emb1, emb2)
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/text2vec/similarity.py", line 163, in cos_sim
    return torch.mm(a_norm, b_norm.transpose(0, 1))
RuntimeError: could not create a primitive descriptor for a matmul primitive

**Comment by shibing624** [comment]
只接受列表。 

```
    def get_scores(
            self, sentences1: List[str], sentences2: List[str], only_aligned: bool = False
    ) -> ndarray:
```
