### ISSUE TITLE
数据下载错误

### ISSUE THREAD

**Issue by HanZhang-LiXin** [shibing624/text2vec#15]
>>> res = text2vec.encode(char)
[  DEBUG 20200901 12:02:36 word_embedding:82] load w2v embedding ...
Downloading data from https://www.borntowin.cn/mm/emb_models/light_Tencent_AILab_ChineseEmbedding.bin
Traceback (most recent call last):
  File "/Users/lixin/opt/anaconda3/lib/python3.7/site-packages/text2vec/utils/get_file.py", line 281, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/Users/lixin/opt/anaconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/lixin/opt/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/lixin/opt/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/lixin/opt/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/lixin/opt/anaconda3/lib/python3.7/urllib/request.py", line 569, in error

**Comment by shibing624** [comment]
see https://github.com/shibing624/text2vec/issues/16
