### ISSUE TITLE
AttributeError with gensim=4.0.0

### ISSUE THREAD

**Issue by Anthonyive** [shibing624/text2vec#19]
### Describe the bug
Cannot encode embeddings

### To Reproduce
Created a virtual environment using pipenv.
`pipenv install text2vec`
下载了 model
用的是 README.md get text vector and get similarity score between text1 and text2

### Describe your attempts
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not a duplicate issue

### Context
 - **OS**: macOS 11.2.3
 - **Hardware**: CPU only 

In addition, figure out your version by running `import text2vec; text2vec.__version__`.

```
>>> import text2vec; text2vec.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'text2vec' has no attribute '__version__'
>>> dir(text2vec)
['EmbType', 'Path', 'SearchSimilarity', 'SimType', 'Similarity', 'USER_DATA_DIR', 'USER_DIR', 'VEC', 'Vector', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'algorithm', 'embeddings', 'encode', 'processors', 'set_log_level', 'set_stopwords_file', 'similarity', 'utils', 'vector']
```

<details>
  <summary>Code and Error details</summary>

  ```python
  Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52)
  [Clang 6.0 (clang-600.0.57)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> from text2vec import Similarity
  >>> a = 'Creepy'
  >>> b= 'Scary'
  >>> sim = Similarity()
  >>> sim.get_score(a,b)
  /Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
    warnings.warn(msg)
  [  DEBUG 20210414 12:40:06 word_embedding:85] load w2v embedding ...
  [  DEBUG 20210414 12:40:08 word_embedding:114] load w2v from /Users/anthony/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin, spend 1.9008758068084717 s
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/similarity.py", line 60, in get_score
      token_1 = self.tokenize(text1)
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/vector.py", line 60, in tokenize
      self.load_model()
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/vector.py", line 48, in load_model
      self.model = WordEmbedding(w2v_path=self.w2v_path,
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/embeddings/word_embedding.py", line 90, in __init__
      self._build_token2idx_from_w2v()
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/embeddings/word_embedding.py", line 122, in _build_token2idx_from_w2v
      for token in w2v.index2word:
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 634, in index2word
      raise AttributeError(
  AttributeError: The index2word attribute has been replaced by index_to_key since Gensim 4.0.0.
  See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4
  >>> import text2vec
  >>> char = '卡'
  >>> result = text2vec.encode(char)
  [  DEBUG 20210414 12:40:53 word_embedding:85] load w2v embedding ...
  [  DEBUG 20210414 12:40:54 word_embedding:114] load w2v from /Users/anthony/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin, spend 1.3408758640289307 s
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/vector.py", line 67, in encode
      self.load_model()
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/vector.py", line 48, in load_model
      self.model = WordEmbedding(w2v_path=self.w2v_path,
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/embeddings/word_embedding.py", line 90, in __init__
      self._build_token2idx_from_w2v()
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/text2vec/embeddings/word_embedding.py", line 122, in _build_token2idx_from_w2v
      for token in w2v.index2word:
    File "/Users/anthony/.local/share/virtualenvs/test-Cj2sK_tx/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 634, in index2word
      raise AttributeError(
  AttributeError: The index2word attribute has been replaced by index_to_key since Gensim 4.0.0.
  See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4
  >>> text2vec.__version__
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  AttributeError: module 'text2vec' has no attribute '__version__'
  >>> import text2vec; text2vec.__version__
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  AttributeError: module 'text2vec' has no attribute '__version__'
  >>> dir(text2vec)
  ['EmbType', 'Path', 'SearchSimilarity', 'SimType', 'Similarity', 'USER_DATA_DIR', 'USER_DIR', 'VEC', 'Vector', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'algorithm', 'embeddings', 'encode', 'processors', 'set_log_level', 'set_stopwords_file', 'similarity', 'utils', 'vector']
  ```
</details>

**Comment by shibing624** [comment]
pip install gensim==3.5.0
