### ISSUE TITLE
'编程语言'、'活泼开朗'等词出现错误：KeyError: "Key '编程语言' not present"

### ISSUE THREAD

**Issue by lz-xinlin** [shibing624/text2vec#22]
Traceback (most recent call last):
  File "F:/data-contest/vec_text.py", line 11, in <module>
    s = sim.get_score(a, b)
  File "G:\py-env\xiamen-financial-cup\lib\site-packages\text2vec\similarity.py", line 63, in get_score
    emb_1 = self.encode(token_1)
  File "G:\py-env\xiamen-financial-cup\lib\site-packages\text2vec\vector.py", line 72, in encode
    return self.model.embed_one(tokens)
  File "G:\py-env\xiamen-financial-cup\lib\site-packages\text2vec\embeddings\embedding.py", line 127, in embed_one
    return self.embed([sentence])[0]
  File "G:\py-env\xiamen-financial-cup\lib\site-packages\text2vec\embeddings\word_embedding.py", line 193, in embed
    emb.append(self.w2v.get_vector(word, norm=True))
  File "G:\py-env\xiamen-financial-cup\lib\site-packages\gensim\models\keyedvectors.py", line 422, in get_vector
    index = self.get_index(key)
  File "G:\py-env\xiamen-financial-cup\lib\site-packages\gensim\models\keyedvectors.py", line 396, in get_index
    raise KeyError(f"Key '{key}' not present")
KeyError: "Key '编程语言' not present"

**Comment by shibing624** [comment]
请更新到最新版本代码，0.1.8已经解决该问题。https://github.com/shibing624/text2vec/commit/cc9458b22c41f523f11f83d837c0ec2eeabe46b7
