### ISSUE TITLE
Minimal working example Failure: ValueError

### ISSUE THREAD

**Issue by FranklinBao** [shibing624/text2vec#26]
### In version 0.1.9
[  DEBUG 20210806 09:56:30 word_embedding:71] load w2v embedding ...
Traceback (most recent call last):
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-21a0e738843e>", line 1, in <module>
    text2vec.encode("我")
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/text2vec-0.1.9-py3.7.egg/text2vec/vector.py", line 69, in encode
    self.load_model()
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/text2vec-0.1.9-py3.7.egg/text2vec/vector.py", line 55, in load_model
    stopwords_file=self.stopwords_file)
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/text2vec-0.1.9-py3.7.egg/text2vec/embeddings/word_embedding.py", line 76, in __init__
    self._build_token2idx_from_w2v()
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/text2vec-0.1.9-py3.7.egg/text2vec/embeddings/word_embedding.py", line 98, in _build_token2idx_from_w2v
    w2v = KeyedVectors.load_word2vec_format(self.w2v_path, **self.w2v_kwargs)
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1632, in load_word2vec_format
    limit=limit, datatype=datatype, no_header=no_header,
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1903, in _load_word2vec_format
    vocab_size, vector_size = [int(x) for x in header.split()]  # throws for invalid file format
  File "/Users/baofanglong/opt/anaconda3/envs/testField/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1903, in <listcomp>
    vocab_size, vector_size = [int(x) for x in header.split()]  # throws for invalid file format
ValueError: invalid literal for int() with base 10: '<!DOCTYPE'

### Attempts

-用pip和下载源码安装出现同样问题，同时曾出现下载超时
 The same issue appears using pip and resource code, and a download timeout error appears before.

-手动从Google Drive 下载失败
 failed when download from google drive manually.

**Comment by shibing624** [comment]
请手动从百度云下载轻量化腾讯词向量，下载后置于：~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin
