### ISSUE TITLE
句子向量计算的OOV问题

### ISSUE THREAD

**Issue by etrigger** [shibing624/text2vec#5]
如何处理没有出现在词向量的句子，会出现下面的错误
比如输入全角逗号"，", 轻量版腾讯词向量中没有对应向量，有可能大的“腾讯词向量”包含，但我想请教万一有没包含的如何处理

text2vec/embeddings/word_embedding.py:184: RuntimeWarning: invalid value encountered in true_divide
avg_tensor_x = np.divide(tensor_x, count)

**Comment by shibing624** [comment]
fix zero bug with https://github.com/shibing624/text2vec/commit/0f9e464ec7f6a42989a253b7ee6ef2906ccb3ea3
设置没出现的是0.0

**Comment by etrigger** [comment]
对于w2v-light-tencent-chinese里没有出现的词条，比如“特价机票”，有没有可能重新计算出来一个新的embedding，要不然直接返回0对于一个实际应用可能无法接受

**Comment by etrigger** [comment]
我加载下载好的Tencent_AILab_ChineseEmbedding.tar.gz总是出错：
from text2vec import Similarity
path = "Tencent_AILab_ChineseEmbedding.tar.gz"
sim = Similarity(w2v_path=path)
=====================================================
[  DEBUG 20200214 04:07:29 word_embedding:82] load w2v embedding ...
Traceback (most recent call last):
  File "check_text_similarity.py", line 12, in <module>
    s2 = sim.get_score(a, c)
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/text2vec/similarity.py", line 58, in get_score
    token_1 = self.tokenize(text1)
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/text2vec/vector.py", line 54, in tokenize
    self.load_model()
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/text2vec/vector.py", line 47, in load_model
    trainable=self.trainable)
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/text2vec/embeddings/word_embedding.py", line 86, in __init__
    self._build_token2idx_from_w2v()
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/text2vec/embeddings/word_embedding.py", line 108, in _build_token2idx_from_w2v
    w2v = KeyedVectors.load_word2vec_format(self.w2v_path, **self.w2v_kwargs)
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 1498, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 343, in _load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/root/miniconda3/envs/py3.6/lib/python3.6/site-packages/gensim/utils.py", line 359, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte

**Comment by shibing624** [comment]
1. fix oov with https://github.com/shibing624/text2vec/commit/ec5f116ef7f968ef43a2d59d506def76f67bb8f6,新增长词再拆分来估计该词向量。相似度计算结果如下：

，机票 特价机票 0.8837044884558658
机票 特价机票 0.8837044884558658
具体结果详见测试用例。
2. w2v_path 是指 bin文件路径，tar包解压缩再指定。如果是使用程序指定的模型文件，会自动下载并解压缩。

**Comment by etrigger** [comment]
好的，谢谢
Tencent_AILab_ChineseEmbedding.txt这个太大了，加载了好久。我是不是可以从Tencent_AILab_ChineseEmbedding.txt里面抽取若干行我需要的？另外，抽取完了如何像你一样写成二进制文件，是否有代码可以借鉴。谢谢

**Comment by shibing624** [comment]
1.可以抽取部分行，轻量版就是我抽取的高频词，高query词。
2.抽取方法通过词过滤就好了，保存为二进制通过KeyedVectors的save就可以，不懂可以参考gensim库的说明文档。

**Comment by xxllp** [comment]
你这个高频词模型 里面有多少个词

**Comment by shibing624** [comment]
$ head light_Tencent_AILab_ChineseEmbedding.bin    
143613 200

143613个词，每个词向量是200维。

**Comment by xxllp** [comment]
我现在本地github下载这个bin文件速度很慢 有网盘等国内下载的地址吗 多谢~~~

**Comment by shibing624** [comment]
暂没其他地址

**Comment by xxllp** [comment]
我已经解决了 ~~~
