### ISSUE TITLE
运行 api server： python jina_server_demo.py报错   ModuleNotFoundError

### ISSUE THREAD

**Issue by alexhmyang** [shibing624/text2vec#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

(pytorch) E:\text2vec\examples>python jina_server_demo.py
DeprecationWarning: pkg_resources is deprecated as an API (raised from C:\Users\86187\.conda\envs\pytorch\lib\site-packages\pkg_resources\__init__.py:121)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages (raised from C:\Users\86187\.conda\envs\pytorch\lib\site-packages\pkg_resources\__init__.py:2870)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages (raised from C:\Users\86187\.conda\envs\pytorch\lib\site-packages\pkg_resources\__init__.py:2870)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages (raised from C:\Users\86187\.conda\envs\pytorch\lib\site-packages\pkg_resources\__init__.py:2870)
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages (raised from C:\Users\86187\.conda\envs\pytorch\lib\site-packages\pkg_resources\__init__.py:2349)
UserWarning: DistributionNotFound(Requirement.parse('pytest==6.2.4'), None) (raised from
C:\Users\86187\.conda\envs\pytorch\lib\site-packages\hubble\executor\helper.py:698)
Traceback (most recent call last):
  File "E:\text2vec\examples\jina_server_demo.py", line 15, in <module>
    with f:
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\orchestrator.py", line 14, in __enter__
    return self.start()
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\flow\builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\flow\base.py", line 1830, in start
    self.enter_context(deployment)
  File "C:\Users\86187\.conda\envs\pytorch\lib\contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\orchestrator.py", line 14, in __enter__
    return self.start()
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\deployments\__init__.py", line 1008, in start
    self.enter_context(self.shards[shard_id])
  File "C:\Users\86187\.conda\envs\pytorch\lib\contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\deployments\__init__.py", line 112, in __enter__
    pod = PodFactory.build_pod(_args).start()
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\jina\orchestrate\pods\factory.py", line 39, in build_pod
    cargs.uses = HubIO(_hub_args).pull()
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\hubble\executor\hubio.py", line 1323, in pull
    install_package_dependencies(
  File "C:\Users\86187\.conda\envs\pytorch\lib\site-packages\hubble\executor\hubapi.py", line 109, in install_package_dependencies
    raise ModuleNotFoundError(
ModuleNotFoundError: Dependencies listed in requirements.txt are not all installed locally, this Executor may not run as expect. To install dependencies, add `--install-requirements` or set `install_requirements = True`

### Steps To Reproduce

pip install jina已安装

### Environment

```markdown
- OS: windows
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by shibing624** [comment]
jina 我重新测试了一遍，是可以正确执行的。
```
pip install jina=3.17.0
```
python3.10 的环境。

先起jina_server, 再jina_client请求服务。

执行结果：

![image](https://github.com/shibing624/text2vec/assets/10249622/6c42ac35-95d3-461a-af31-1154c5f4da4e)
